root.calibrate.repair.doInterpolate = False
root.calibrate.repair.doCosmicRay = False
root.calibrate.doAstrometry = True
root.calibrate.doPhotoCal = True
root.calibrate.doPsf = True
root.calibrate.doComputeApCorr = True
root.calibrate.measurePsf.psfDeterminer['pca'].reducedChi2ForPsfCandidates=3.0
root.calibrate.measurePsf.psfDeterminer['pca'].spatialReject=2.0
root.calibrate.measurePsf.psfDeterminer['pca'].nIterForPsf=0
root.calibrate.measurePsf.psfDeterminer['pca'].tolerance=0.01
